"""Add Lunrea app sessions

Revision ID: 07ad164f2326
Revises: ef2cb4dc6fa5
Create Date: 2026-08-17 00:26:50.463166

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '07ad164f2326'
down_revision = 'ef2cb4dc6fa5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('app_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('session_token', sa.String(length=255), nullable=False),
    sa.Column('unlocked_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_activity', sa.DateTime(timezone=True), nullable=False),
    sa.Column('locked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_locked', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('app_sessions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_app_sessions_session_token'), ['session_token'], unique=True)
        batch_op.create_index(batch_op.f('ix_app_sessions_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('app_sessions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_app_sessions_user_id'))
        batch_op.drop_index(batch_op.f('ix_app_sessions_session_token'))

    op.drop_table('app_sessions')
    # ### end Alembic commands ###
