"""Add cascade deletes to album relationships

Revision ID: 1c958720f5b2
Revises: 07ad164f2326
Create Date: 2026-08-21 00:01:50.989272

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1c958720f5b2'
down_revision = '07ad164f2326'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('album_members', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('album_members_album_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'albums', ['album_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('album_memories', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('album_memories_album_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'albums', ['album_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('chapter_memories', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('chapter_memories_chapter_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'chapters', ['chapter_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('chapters', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('chapters_album_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'albums', ['album_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chapters', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('chapters_album_id_fkey'), 'albums', ['album_id'], ['id'])

    with op.batch_alter_table('chapter_memories', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('chapter_memories_chapter_id_fkey'), 'chapters', ['chapter_id'], ['id'])

    with op.batch_alter_table('album_memories', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('album_memories_album_id_fkey'), 'albums', ['album_id'], ['id'])

    with op.batch_alter_table('album_members', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('album_members_album_id_fkey'), 'albums', ['album_id'], ['id'])

    # ### end Alembic commands ###
